### ISSUE TITLE
BUG: ImportError: cannot import name 'styles' from 'neptune.exceptions'

### ISSUE THREAD

**Issue by dzerkes** [neptune-ai/neptune-client#1200]
After installing neptune-client (tried via conda and pip), I tried to import the following:

```
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.model_selection import StratifiedShuffleSplit
import neptune
import neptunecontrib.monitoring.skopt as sk_utils
import lightgbm as lgb
import pandas as pd
import skopt
import sys
import os
import numpy as np
```
which resulted in this error:
**_ImportError: cannot import name 'styles' from 'neptune.exceptions'_**

**How I fixed it** 

I opened the file neptune.exceptions.py 
and change the EMPTY_STYLES to STYLES

OS: Linux Ubuntu 22.04
python version:  3.8

**Comment by Blaizzy** [comment]
Hi @dzerkes 

Prince here,

It looks like you are using the legacy neptune-client which is no longer supported.

To use the latest client you can do the following:
1. Instead of `import neptune` use `import neptune.new as neptune`.
2. Remove `import neptunecontrib.monitoring.skopt as sk_utils`

You can read more about it in our docs.
Docs: 
https://docs.neptune.ai/about/legacy/#initialization

**Comment by Blaizzy** [comment]
Let me know if this helps you
