### ISSUE TITLE
How to access experiment logged experiment data over time in neptune v1+

### ISSUE THREAD

**Issue by stefanbschneider** [neptune-ai/neptune-client#1369]
We are heavily using Neptune for logging ML experiments. The experiments show in the Neptune web app, eg, like this showing values logged over time/steps:
![image](https://github.com/neptune-ai/neptune-client/assets/28340802/1d8089ee-671d-47ed-9aef-7c16f8bad79c)

We also have scripts for fetching and processing the experiment results using the neptune-client. We're having issues upgrading from `neptune` 0.X to 1.X because it's unclear how to fetch the experiment results over time.

We used to get a list of `Experiments` and then retrieve the results from them like this:
```python
experiments: List[Experiment] = project.get_experiments(tag=tag)
# get_numeric_channels_values used to return the whole series of results for the given metric over time
dfs = [exp.get_numeric_channels_values(metric) for exp in experiments]
```

Now, the API is different and `Experiment` is deprecated as is `get_numeric_channel_values`. Instead, I can get a `Table` that I can only retrieve the *last* logged value per entry but no longer all entries logged over time.
```python
# This gives me a Table that I can either use a list of TableEntries or as pandas df
runs_table = project.fetch_runs_table(tag=tags)
# This only gives me the *last* logged value of each run for the given metric; not all values logged over time
runs_table.to_pandas()[metric]
```

How can I get logged values over time with the new API? I did not find any helpful documentation nor any suitable function inside the code. Is it not possible anymore without accessing the legacy code?

**Comment by SiddhantSadangi** [comment]
Hello @stefanbschneider 👋 

To get the logged values over time, you will need to 
1. Fetch the run_id of the run you want to get the values from. Since you already have the runs_table, you can get the IDs by querying the "sys/id" field:
```python
run_ids = runs_table.to_pandas()["sys/id"].values
```
2. [Reinitialize the old run](https://docs.neptune.ai/usage/querying_metadata/#initializing-existing-object) using `with_id=run_id`. I recommended doing this in [`read-only`](https://docs.neptune.ai/logging/to_existing_object/#accessing-objects-in-read-only-mode) mode to avoid modifying the old run:
```python
for run_id in run_ids:
    run = neptune.init_run(project=project, with_id=run_id, mode="read-only")
```

3. And then use [`fetch_values()`](https://docs.neptune.ai/usage/querying_metadata/#querying-values-from-series-field) with the namespace you want to query:
```python
accuracy = run["accuracy"].fetch_values()
```

You can reinitialize the run within a context manager so that it is automatically stopped after you have fetched the relevant metadata:

```python
for run_id in run_ids:
    with neptune.init_run(project=project, with_id=run_id, mode="read-only") as run:
        accuracy = run["accuracy"].fetch_values()
        ...
```

Please let me know if this helps 🤗

**Comment by stefanbschneider** [comment]
Perfect, thank you!

**Comment by stefanbschneider** [comment]
@SiddhantSadangi Your answer works really well, thanks! Just a quick follow-up: I want to use `RunsTable` for typing, but if I import it from `neptune.new`, I get deprecation warning:
```
NeptuneDeprecationWarning: You're importing the Neptune client library via the deprecated `neptune.new` module, which will be removed in a future release. Import directly from `neptune` instead.
  from neptune.new import RunsTable
```

However, `RunsTable` cannot be imported from `neptune` directly. Is there any preferred way for importing it?

**Comment by SiddhantSadangi** [comment]
Hi @stefanbschneider !

`RunsTable` is an alias of the more generic `Table`.

You can import `Table` from `neptune.metadata_containers.metadata_containers_table`:
`from neptune.metadata_containers.metadata_containers_table import Table as RunsTable`

Please let me know if this helps 🙏

**Comment by stefanbschneider** [comment]
It does, thanks! :)

**Comment by SiddhantSadangi** [comment]
Great 🥳 

Please feel free to contact us with any further queries or suggestions.
We are always happy to help 🤗
