### ISSUE TITLE
Feature Request:  Display the actual run name on the tool tip while hovering over run link on left. 

### ISSUE THREAD

**Issue by Sanskar021995** [neptune-ai/neptune-client#1665]
### Is your feature request related to a problem? Please describe.
When there are multiple experiments put to tun together, it becomes difficult to differentiate the names without getting into the run and see the details.
### Describe the solution you'd like
Currently the tooltip displays the same name that is assigned by neptune, this can be changed to the experiment run name.
![image](https://github.com/neptune-ai/neptune-client/assets/150417915/870ed0ed-4f02-432a-818c-0d4df00ad15e)

**Comment by SiddhantSadangi** [comment]
Hey @Sanskar021995 👋 
Are you referring to the custom run name set via `sys/name`? 

You can pin the `sys/name` column to the run table so that it is always visible when you are browsing run details:
![image](https://github.com/neptune-ai/neptune-client/assets/41324509/2539ac66-0bfb-4781-9d53-1df8997d4e13)

Would this help?

**Comment by Sanskar021995** [comment]
Hi @SiddhantSadangi 
Thanks for the response, this is exactly what I was looking for
Thanks!
