### ISSUE TITLE
Feature Request: Increase field count

### ISSUE THREAD

**Issue by simon-ging** [neptune-ai/neptune-client#1884]
Dear neptune team,

### Is your feature request related to a problem? Please describe.

NeptuneFieldCountLimitExceedException: There are too many fields (more than 9000)

I have several datasets, each evaluated with different prompts, and then generating several metrics per prompt. This somewhat quickly generates more than 9000 fields, but I find this limit to be a bit low.

### Describe the solution you'd like

Some way to increase the maximum number of fields

### Describe alternatives you've considered

The alternative would be to not log the metrics to neptune which would defeat the purpose of neptune.

Thanks for considering

**Comment by SiddhantSadangi** [comment]
Hey @simon-ging 👋 

The maximum number of fields is a backend limitation of the current Neptune implementation.
However, the new version of Neptune - Neptune Scale - fixes this issue by doing away with field count limits ✅ 

It is currently in Early Access. You can request access here: https://neptune.ai/early-access

Meanwhile, would it be possible for you to split logging into different runs? For example, can a different run for each dataset be used so that no single run exceeds the field count limit?

**Comment by simon-ging** [comment]
Thanks for the quick response! Turned out it was mainly my config files who became quite big (~500kb yaml) and storing them in neptune caused the problem: `neptune_logger.experiment["config"] = StringifyValue(value=config_dict)` creates thousands of fields if the config_dict is large. I am now uploading only the important parts of the config. And I am also not uploading the test metrics since they are quite many.

So, it's solved for now, and long term the limit will go away as you described. Thanks again.

**Comment by michalsustr** [comment]
Hi @simon-ging , Michal from https://minfx.ai - we have no issues supporting large number of configs!
