### ISSUE TITLE
`log_artifact` fails silently

### ISSUE THREAD

**Issue by Jonas1312** [neptune-ai/neptune-client#243]
I tried to upload my pytorch model weights as an artifact through a BytesIO:

```python
buffer = BytesIO()
print(getsizeof(buffer))  # 96
torch.save(model.state_dict(), buffer)
print(getsizeof(buffer))  # 101291839
experiment.log_artifact(artifact=buffer, destination="fold0.pth")
```

But the artifact is empty (0B) and the python script doesn't crash:

![Screenshot from 2020-06-24 16-40-00](https://user-images.githubusercontent.com/15847892/85577063-39f57480-b639-11ea-9563-e49daeb84c27.png)

**Comment by pitercl** [comment]
Hi @Jonas1312,

the reason for this behaviour is that the position of your `buffer` stream is after what has been written. If you modify your snippet by adding `buffer.seek(0)`, it will work. I'll keep this issue open, because we should include that info in our docs.

Here's the full snippet for completeness:
```py3
buffer = BytesIO()
print(getsizeof(buffer))  # 96
torch.save(model.state_dict(), buffer)
buffer.seek(0)
print(getsizeof(buffer))  # 101291839
experiment.log_artifact(artifact=buffer, destination="fold0.pth")

```

**Comment by Jonas1312** [comment]
Hi @pitercl,

It works! Thanks a lot :)
