### ISSUE TITLE
JsonDecodeError

### ISSUE THREAD

**Issue by ben-heil** [neptune-ai/neptune-client#282]
Hi, I'm running into the same issue that Richard was in https://github.com/neptune-ai/neptune-client/issues/280. I'm creating neptune experiments within a loop testing the same model on multiple subsets of a dataset. 

The model is the same each time and the JsonDecodeError occurs randomly, i.e. the code will run for hours then randomly throw the error.

Sorry if this is the wrong place to post, I would have commented in the other thread but the issue was already closed.

**Comment by ben-heil** [comment]
If it helps, my neptune init code is [here](https://github.com/greenelab/saged/blob/master/saged/subset_label_prediction.py#L53) and the code that creates experiments is [here](https://github.com/greenelab/saged/blob/master/saged/models.py#L502)

**Comment by PiotrJander** [comment]
Hi @ben-heil , thanks for reporting the issue.

We suspect that the error you are experiencing might be due to a bug in https://github.com/Yelp/bravado , which is a dependency used by `neptune-client`.

Could you post the version of `bravado` in the Python environment where you run your experiments (look at the output of `pip freeze`)? If the version is `v10.6.1`, then it would seem to confirm our suspicion, and an update to a newer version should help.

Please let us know how it goes!

**Comment by ben-heil** [comment]
My env is still on 0.4.117, I'll go update it. Thanks!
