### ISSUE TITLE
Logging strings raises InvalidChannelValue

### ISSUE THREAD

**Issue by gabriel-vanzandycke** [neptune-ai/neptune-client#386]
neptune.log("key", "value")
raises
```
neptune.exceptions.InvalidChannelValue: Invalid channel value type. Expected: float, actual: str.
```

**Comment by PiotrJander** [comment]
Hi @gabriel-vanzandycke , I'll try to help:

There is no `neptune.log` method. I believe you must have tried `neptune.log_metric("key", "value")`, which will indeed raise this exception since `log_metric` only logs numeric values (so `neptune.log_metric("key", 1.23)` would work, for example).

To log a piece of text / a string, use `log_text`: `neptune.log_text("key", "value")`
