### ISSUE TITLE
Neptune.new API appends '.h5' to path when downloading a model?

### ISSUE THREAD

**Issue by ljburtz** [neptune-ai/neptune-client#496]
![image](https://user-images.githubusercontent.com/26211495/113959322-9be83900-985d-11eb-8a21-f9caef379912.png)

as shown in this minimal example, the path of the file downloaded via Neptune.new does not match the path specified. And does not match the path in the Neptune UI either :
![image](https://user-images.githubusercontent.com/26211495/113959464-e5388880-985d-11eb-830a-f0dc6e4cb0c6.png)

Does not match = has an extra `.h5` appended to it.

And of course, If I remove the '.h5' from the .download query, then neptune raises `ValueError: Could not find model/best_model_iou attribute`

Thank you for your help investigating this issue

**Comment by HubertJaworski** [comment]
Hi,

Thanks for reporting this!

We've identified the issue on our part and we're currently discussing solution internally.

Most propably we'll solve this server side, but a client update might be required after our fix.

Best,
Hubert

**Comment by PiotrJander** [comment]
Hi @ljburtz 

I suppose that you might have uploaded the file like this:

```
run["dataset/best_model_iou.h5"].upload("best_model_iou.h5")
```

The intended way to upload files is like this:

```
run["dataset/best_model_iou"].upload("best_model_iou.h5")
```

^ notice that the extension is omitted within square braces.

I will note your confusion as a usability problem - we will let you know when this gets addressed.

**Comment by Herudaio** [comment]
👋🏻  @ljburtz 
It's a bit of a change of the mental model from the previous version of Neptune. 

In the legacy, version Artifacts could have been explained as a file system-like functionality and were mimicking it very closely. What you did upload was saved under the same name with the extension etc. We later added integrations with interactive charting libraries and it was a bit more confusing. Are the artifacts just files? How so if there are visualizations (Interactive visualization as HTML)? Why aren't those in the same place?

The mental model behind the new Python API is more database-like. We have a field (with a path) and under it, we store some content - Float, String, series of String, or File. In this model extension is part of the content. An example use case would be following:
`run['model/architecture'].upload(File.as_image(static_fig))` <- this will be a PNG file
`run['model/architecture'].upload(File.as_html(interactive_chart))` <- this will be an interactive HTML file
Later on, you can create a dashboard that uses the field 'model/architecture' and it will show models architecture regardless of the type of visualization. The trade-off is that the interaction with pure files can be a bit less intuitive, and it's a trade-off we made consciously. 

That being said as @PiotrJander mentioned there is a usability problem that we want to solve - if you don't know what you did upload you don't know the extension and the filename of the downloaded file is not fully known upfront.
1. We will add the option to learn extension through code (we are still figuring it naming for method - it's the hardest as usual ;))
2. We will add an optional parameter with the target filename. So that integrating Neptune in any workflow is easier as you don't have to move around or rename the file :)

I hope this clears up a bit @ljburtz and please expect changes 1 & 2 next or next-next week :)

**Comment by ljburtz** [comment]
Thanks a lot for the three replies and your perspectives so I can understand deeply.
Understood for the change of mental model -> no problem as long as it's documented.
I look forward to the usability improvements you mentioned too, thanks for making a great product! I'll keep a lookout on the changelog
