### ISSUE TITLE
Increasing stdout character limit

### ISSUE THREAD

**Issue by kubouch** [neptune-ai/neptune-client#545]
I'm experiencing the following error after calling [torchinfo.summary](https://github.com/tyleryep/torchinfo):
```
ERROR:neptune.new.internal.operation_processors.async_operation_processor:Error occurred during asynchronous operation processing: Invalid point for string series: monitoring/stdout : Text longer than 1000 characters was truncated
```
It seems like printing the model summary exceeds the maximum allowable string length. Is there a way to increase the limit?

**Comment by Herudaio** [comment]
Hi @kubouch !

The majority of the stdout is way shorter so that's why we set this value as a limit. Typically stdout is used as a monitoring/debugging tool the text is truncated, but it is logged.

There are two good ways to log torchinfo.summary:
`model_summary = summary( [...] )`
1. Break summary into lines and [log](https://docs.neptune.ai/api-reference/field-types#log-1) it as a StringSeries
`run['model/summary'].log(model_summary.split('\n'))`
`.log` method accepts collections and will log each line as a separate entry
2. Log [the summary as a text file](https://docs.neptune.ai/api-reference/field-types#from_content):
`from neptune.new.types import File`
`run['model/summary'].upload(File.from_content(model_summary))`
