### ISSUE TITLE
Timeout related errors after release of 0.9.12

### ISSUE THREAD

**Issue by ReneeErnst** [neptune-ai/neptune-client#567]
I'm now getting these errors after the most recent release (5 hours ago). Given the content of the PR for that release, it seems related. 

![Screen Shot 2021-05-20 at 1 15 28 PM](https://user-images.githubusercontent.com/13136940/119029526-58114500-b96e-11eb-8ee2-e771bd09bc56.png)

**Comment by aniezurawski** [comment]
Hi @ReneeErnst 

I don't think it is related to last release. This bug is known for few days already but it is not very common so it is not easy to reproduce it. We are still investigating the issue but I hope it's going to be fixed soon.
Just to be sure it's the same problem I am aware of can you share with us what exception was raised?

**Comment by HubertJaworski** [comment]
Hi, thank you for reporting this!

It's most propably caused by https://github.com/websocket-client/websocket-client/issues/694

Can you downgrade websocket-client to previous version and see if it works for you?

`pip install websocket-client==0.59.0`

It helped me - if this is indeed a broken version of websocket-client, we'll fix our requirements to exlude this version

**Comment by ReneeErnst** [comment]
Thank you! Just very odd timing then, since I was building images all day yesterday and then today the error popped up! I would have thought that if this has been around a few days, I would have hit it with my fresh images yesterday. Odd. But I'll try this solution and report back.

**Comment by ReneeErnst** [comment]
I was able to confirm that just rolling back to Neptune 0.9.11 didn't solve the problem, but adding `websocket-client==0.59.0` to my requirements did!
