### ISSUE TITLE
upload() doesn't work in distributed settings

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ai/neptune-client#575]
Code:
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from time import time, sleep

import neptune.new as neptune
from neptune.new.types import File
import ray 


@ray.remote
def f(x, run_id):
    run = neptune.init('nnaisense/sandbox-new', run=run_id,
                       monitoring_namespace=f'monitoring/{x}',
                       source_files=[])
    run[f'results/{x}'].upload(File(content=b'asdfa', extension='bin'))


def main():
    n_jobs = 2 
    run = neptune.init(
        'nnaisense/sandbox-new',
        name='name',
        description='',
        source_files=[],
        flush_period=10,
        mode='async',
        monitoring_namespace='monitoring/main'
    )   

    rid = run['sys/id'].fetch()
    run['params/main'] = {'asdf': 2}

    ray.init()
    ray.get([f.remote(i, rid) for i in range(n_jobs)])


if __name__ == '__main__':
    main()
```

No file will be uploaded to `results` unless you set `wait=True`.

**Comment by HubertJaworski** [comment]
Hi @wjaskowski 

My investigation leads me to a conclusion that `ray` does not call proper shutdown logic.

Neptune relies on `atexit` handler to be called an the end of (sub)process to perform the `run.stop()` operation to send remaining async operations to server, and since `ray` does not trigger the handler, Neptune cannot do this.

Fun fact: adding sleep(5) at the end of your `main` lets Neptune have enough time to upload before workers are badly killed

For your use-case, I'd suggest using something like 
```
@ray.remote
def f(x, run_id):
    with neptune.init(run=run_id,
                       monitoring_namespace=f'monitoring/{x}',
                       source_files=[]) as run:
        run[f'results/{x}'].upload(File(content=b'asdfa', extension='bin'))
```
Using `with` block ensures that at the end of it `run.stop()` before `ray.get` returns

BTW, did you know that you can set `NEPTUNE_PROJECT` environemntal variable to set the default project name to use in `neptune.init()` call? It'll allow you to skip the project name parameter and create more flexible code.

I searched our docs, but didn't find any mention of it, I'll ping someone on the team to add a line or two about it

**Comment by wjaskowski** [comment]
@HubertJaworski Thx for investigating that. Is it that issue: https://github.com/ray-project/ray/issues/12806? Maybe this is already fixed in https://github.com/ray-project/ray/pull/12808/commits/95589e7c5c4575a1bfa8b21bc8bbeb36a7af8f38 but not released yet.

Also thx for the hint on `with` construction. I think it is better than mine wait since I would need to do wait everywhere to be robust and this is inefficient, of course. I think `with` is also not documented.

I have been aware of NEPTUNE_PROJECT in the previous version. Here, I have a more complicated scenario when I will use two neptune projects in a single program so I handle this differently.

**Comment by HubertJaworski** [comment]
This ray bug looks exactly like the behaviour we're observing here.

I've let the team know that `with neptune.init() as run:` is not documented, thx for letting us know

**Comment by pkasprzyk** [comment]
@wjaskowski the issue you've referenced seems to have been fixed with ray-1.2.0, released 2021-02-13 : https://github.com/ray-project/ray/pull/12808

I can't find info about the ray version you were using, though. If you're still using ray, can you confirm the problems are gone?

**Comment by wjaskowski** [comment]
I haven't encountered them since I started using the `with` construction with Neptune. Feel free to close.

**Comment by pkasprzyk** [comment]
thanks!
