### ISSUE TITLE
Neptune Uploads Suddenly Slowed Down

### ISSUE THREAD

**Issue by HoltSpalding** [neptune-ai/neptune-client#600]
Hello, I've been using Neptune.ai for a few months now. When I started using the service, experiments would be logged asynchronously and pretty much in real time during model training (using tf keras). I reinstalled the neptune client in a new python environment and suddenly its taking almost an hour per experiment to upload all the logs. I can provide some more context, but what factors might I look at that could have caused this behavior (mind you, I haven't changed any code).  I switched by the way from neptune-client 0.9.1 to 0.9.6. Do you have any performance metrics regarding upload speeds?

**Comment by shnela** [comment]
So right now your experiments slowed down from from real time upload to about one hour lag, right?
Could you please check if you've downgraded to `neptune-client==0.9.1` you can see performance improvements, so we could tell if performance drop was caused by `neptune-client` version change or some other environment related parameters.
Have you've tested any recent versions of `neptune-client`? The newest one is `0.9.18`.

Best,
Jakub

**Comment by pkasprzyk** [comment]
@HoltSpalding have you found out anything more about your issue? Is it still occurring?
