### ISSUE TITLE
BUG: sequence of offline run IDs

### ISSUE THREAD

**Issue by cemde** [neptune-ai/neptune-client#838]
### Describe the bug
When starting offline runs with pytorch lightning interface, the run name  will always be "OFFLINE-1" but does not increase based on the runs that are locally stored in the .neptune folder.

### Reproduction
start a run in offline mode.
start another run in offline mode.
both will have name "OFFLINE-1".
In as much detail as possible, please provide steps to reproduce the issue or code snippet.

### Expected behavior

naming in a sequence "OFFLINE-1", "OFFLINE-2",...

### Environment

neptune version 0.14.2
pytorch lightning 1.5.9

**Comment by Blaizzy** [comment]
I got it,

It's not that the name of the run is going to be OFFLINE-1,

Your runs' metadata are saved inside '.neptune/offline', you checked `'.neptune/offline-name'` that has a folder inside called OFFLINE-1. This is the folder where your model checkpoints are saved if you don't specify path for them, as when pass the dirpath to ModelCheckpoint Callback for example.

- .neptune
     - offline - > tracked runs
     - offline-name -> default path for checkpoints  

For example:

I created two runs and if I look inside `'.neptune/offline'` I get:

- 140c6f94-a1cd-4b62-ad43-73df77df6169  
- 371205f9-59c8-42fc-9f42-1928f29b71bb

Which are my two offline tracked runs.

While inside `'.neptune/offline-name/OFFLINE-1/checkpoints'` I get my model checkpoints:

- 'epoch=1-step=1875.ckpt'    
- 'epoch=1-step=1875-v1.ckpt'

**Solution** ✅ 
If you specify the path in your ModelCheckpoint Callback the path `'.neptune/offline-name'` will not exist because PTL will now use the path you passed to ModelCheckpoint to save checkpoints.

Example:

```
checkpoint_callback = ModelCheckpoint(dirpath="/your/path")

trainer = Trainer(
    ...
    logger=neptune_logger,
    callbacks=[checkpoint_callback]
)
```

You checkpoints will be saved inside '/your/path'.

- your/path
     - ...
     - epoch=N-step=N.ckpt

**Comment by Blaizzy** [comment]
Let me know if this helps you! 😃

**Comment by Blaizzy** [comment]
Hey @cemde 

Any updates?
