### ISSUE TITLE
Feature Request: use custom_run_id to change the run id

### ISSUE THREAD

**Issue by tshu-w** [neptune-ai/neptune-client#876]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when I want to use `custom_run_id` to change the `sys/id` of `run`, However the `project-key` with number is still used as the run id and I cannot find custom_run_id in metadata.

Here is the code to reproduce:
```python
import neptune.new as neptune

run = neptune.init(
    project="username/project-name",
    api_token="API_TOKEN",
    custom_run_id="04-02T210902",
)
```

### Describe the solution you'd like
Users can use `custom_run_id` to change the run id.

### Describe alternatives you've considered
`custom_run_id` saved in the metadata.

**Comment by Blaizzy** [comment]
Hi @tshu-w 

Prince Canuma here, a Data Science at neptune.ai

Thank you for your patience!

Unfortunately, you can't change the `sys/id` that is fixed because of the DB and currently we don't display the custom_run_id in the run automatically, but you can log it as text, like so:

`run["custom_run_id"] = <your_custom_run_id>`

Would mind helping me understand your use case for replacing the `sys/id` with `custom_run_id`?

**Comment by tshu-w** [comment]
I was hoping to align the id in PL logger with the one in Neptune. I can understand that id and custom_run_id are not the same thing. But custom_run_id needs to be logged before it is displayed I think it is a bit unreasonable or needs to be raised in the documentation.

**Comment by Blaizzy** [comment]
Thank you for the feedback!

I will send it to the product team.

It's part of our roadmap to expose the custom_run_id
Read more here: https://portal.neptune.ai/c/95-exposing-sys-custom_run_id

**Comment by Blaizzy** [comment]
For now you can log it manually! 😃
